fix: checkout types
NuroDev/lemonsqueezy.ts pull request #20
Opened 2023-06-30 11:19 UTC by carstenlebek

Made optional fields optional,  added `subscription_preview` and fixed the type for `custom`

2023-07-03 08:44 UTC, NuroDev commented
Thanks for the work on this @carstenlebek  🙏. I am going to have a full look through the changes shortly.

On quick glance I can see a lot of code formatting changes. I have just update `main` to include a Prettier config & a `format` command to fix any formatting issues. Please pull the changes & run the `format` command so everything can stay consistant.

2023-07-04 14:43 UTC, carstenlebek commented
Sorry, my bad 🤦🏼‍♂️ fixed the formatting issues

2023-07-04 17:48 UTC, NuroDev requested changes
Overall looks pretty good. A few small things then should be good to merge:

- Minor code suggestions
- Add tests to `src/client/client.test.ts`
- Add the `/customer` export to `package.json`

2023-07-04 17:48 UTC, NuroDev commented on src/modules/checkout/checkout.types.ts
> +   * If false, hide the "You will be charged..." subscription preview text
```suggestion
   * If `false`, hide the "You will be charged..." subscription preview text
```

2023-07-04 17:48 UTC, NuroDev commented on src/modules/customer/customer.action.ts
> +import {
```suggestion
import type {
```

2023-07-04 21:12 UTC, carstenlebek commented
All done 🥳

2023-07-13 14:13 UTC, NuroDev approved these changes

2023-07-13 14:14 UTC, merged